Template adjunction to have automatic integration testing and everything that comes with it
dataiku/dss-plugin-template pull request #2
Opened 2021-02-01 10:05 UTC by NicolasTriquenaux

2021-02-01 13:43 UTC, alexcombessie approved these changes

2021-02-02 13:45 UTC, alexcombessie requested changes
It all looks good from the code side. I am just wondering why it shows up as red in Jenkins?
http://localhost:13456/jenkins/job/Dataiku/job/dss-plugin-template/view/change-requests/job/PR-2/

Could we fix that before merging?

2021-03-04 08:40 UTC, NicolasTriquenaux commented
@alexcombessie : i'will change that once we have the setup operationnal

2021-04-06 10:22 UTC, alexcombessie approved these changes

2021-04-06 14:09 UTC, merged